# Generated by Django 2.2 on 2019-04-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190419_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Caterogia',
        ),
        migrations.AlterField(
            model_name='jornal',
            name='categorias',
            field=models.ManyToManyField(to='core.Categoria'),
        ),
        migrations.AlterField(
            model_name='jornal',
            name='data_publicada',
            field=models.DateTimeField(),
        ),
    ]
