# Generated by Django 2.2 on 2019-04-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190424_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornal',
            name='data_publicada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
