# Generated by Django 2.2 on 2019-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190424_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornal',
            name='data_publicada',
            field=models.DateField(),
        ),
    ]
